### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by maksimanom** [ramsatt/Ionic4gMaps#1]
Hello. I have a "Cannot GET" error and " ERROR in Could not resolve module ./simple/simple.module relative to app\app-routing.module.ts
" in console. Can you help me?
Api key in index.html changed to my own

**Comment by CristianDallos** [comment]
Hi, maksimanom!

Just remove the line in the routing file, this module does not exist in this app and doesn't forget to activate service in google account.

**Comment by ramsatt** [comment]
I am working on it. please wait for a moment

**Comment by ramsatt** [comment]
Issue fixed. Files updated.
